### ISSUE TITLE
Age range for Confirmation events

### ISSUE THREAD

**Issue by WGroleau** [vesta-webtrees-2-custom-modules/vesta_research_suggestions#36]
"Age range for Confirmation events" cannot be set lower than 10.  Is Roman Catholic first communion considered such an event?  My first wife and sister-in-law did theirs when they were nine years old.

**Comment by ric2016** [comment]
No, first communion would be a FCOM event, confirmation is a CONF event.

FCOM is currently not supported in research suggestions, mainly because I don't have those events in my personal tree ;-)
Are first communions recorded in catholic church books? In that case, it makes sense to add them separately.

**Comment by WGroleau** [comment]
OK, I was thinking you were using "confirmation" as a general category like birth and death.

**Comment by ric2016** [comment]
Just to clarify: In any case the age range only affects the research suggestions - You can still add events outside the configured date range to individuals.
