### ISSUE TITLE
results cannot be loaded

### ISSUE THREAD

**Issue by pascal-louis** [vesta-webtrees-2-custom-modules/vesta_research_suggestions#9]
Hello,
After having updated the latest versions of Webtree and the Vesta, it became impossible to search the available sources when entering in the field reserved for this purpose.
Message that appears: "results cannot be loaded".
But I delete the vesta resaerch module, everything is OK again.

Yours sincerely
Pascal

**Comment by ric2016** [comment]
The latest version of webtrees is the latest release 2.0.10 - or the dev code? And this worked correctly for you with earlier versions?
Can you check via browser developer tools what the actual server response is in the case of "results cannot be loaded"?
Do you actually use the functionality of the Vesta module, that is, have you added DATA.EVEN to some of your sources?

**Comment by ric2016** [comment]
Here's a screenshot from firefox that shows what we're looking for - In your case, the Response likely contains some kind of php error message.

![firefox](https://user-images.githubusercontent.com/18174787/97475176-35c1c680-194d-11eb-82bb-a07d3c7a86d9.png)

**Comment by pascal-louis** [comment]
Hi,
It's marked 502 Bad Gateway
My version of Webtree is the latest release 2.0.10 and no problem with the version 2.0.9 of webtree and Vesta
and for the data even, I have only, for example, "1 TITL Abondant (Eure-et-Loir) - Etat civil - Registres des naissances" noted in SOURCE to which I have only added the archive repository

Having said that, I'm not sure I can help you any more, given my level of English and computer skills!

Yours sincerely

**Comment by pascal-louis** [comment]
![capture](https://user-images.githubusercontent.com/67266358/97479902-fc8c5500-1952-11eb-83ca-69cd9bf4c5b9.jpg)

**Comment by ric2016** [comment]
"Bad Gateway" is an unexpected error here. It looks more like something caused by your webserver than by webtrees or the custom module itself.

[Further googling shows threads with similar issues](https://www.000webhost.com/forum/t/502-bad-gateway-openresty-again/109941). [And here](https://www.000webhost.com/forum/t/502-bad-gateway-openresty-randomly-occurs/118628). [And here](https://github.com/kubernetes/ingress-nginx/issues/4609). 

Are there any other areas in webtrees where you encounter this error?
Does this occur in other browsers as well?
Does it occur immediately, or after some time (which may indicate a timeout)?

> Having said that, I'm not sure I can help you any more, given my level of English and computer skills!

No problem, you can answer in French if you prefer, I'll use a translation service.

**Comment by pascal-louis** [comment]
Hello,

The error persists whatever the chosen browser, whether wifi, ethernet or 4G (PC, smartphone...).

I even restarted my internet box, completely empty the history, cached data, cookies...

A curious thing: I noticed that this error appears every time I write a date (of death for example) whatever the form (07/01/1867 or 17-01-1867 or 17.01.1867 or 17 JAN 1867 or via the calendar).

If I erase the date, then there, the error disappears?!

The error also disappears if I delete Vesta Research. 

Sincerely

Pascal

Translated with www.DeepL.com/Translator (free version)

**Comment by pascal-louis** [comment]
In fact, if I want the search in the source field to be done with the Vesta Research module, I have to delete the date, do my search of already existing sources and once I save the date!

I add that this problem seems to affect only the "Source" area.

**Comment by ric2016** [comment]
> If I erase the date, then there, the error disappears?!
> The error also disappears if I delete Vesta Research.

All of this is not surprising, because in these cases the standard webtrees search functionality is used.

Anyway, apparently your webserver masks internal server errors by returning a 502 response code. That is not helpful for debugging. You may have to disable this temporarily in order to determine the actual error. Or check your webserver logs, and/or make sure php errors are logged to the php error log file.

I'm afraid I cannot do anything without an actual error message. The workaround would be to permanently disable this specific Vesta module - it seems you aren't using its functionality anyway?

**Comment by pascal-louis** [comment]
It is true that I do not use all the functions of the module because my site having been created recently, I always made sure to save the sources as I go along.

However, it always tickles me when a bug occurs!

Especially since all your other modules are operational even if I haven't yet understood all aspects of them!

And as I appreciate their qualities, I'm a bit saddened by this...

I'll see in future updates if the problem remains!

In any case, thank you for your modules and the development work it represents.

Sincerely

Pascal

Translated with www.DeepL.com/Translator (free version)

**Comment by ric2016** [comment]
Thank you - I don't like to keep an issue like this open either, but I have no idea how to fix it without additional information. I see that I didn't mention that I cannot reproduce it in any way.

You say that it didn't occur in earlier versions. Have you changed anything else (php version, database) since then?
You can also try to re-upload the module, in case some file is missing. The 2.0.9 Vesta Release should also work with webtrees 2.0.10, although I don't expect that to change anything.
